apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-k8s
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2